import Link from 'next/link'
import './globals.css'

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <nav className="p-4">
          <Link href="/">Home</Link>
        </nav>
        <div className="p-4">{children}</div>
      </body>
    </html>
  )
}

export default RootLayout
